alias: "Heating Optimization: Morning Switch ON"
description: "Turns heating on at the ML-computed optimal time"
triggers:
  - trigger: time
    at: input_datetime.heating_switch_on_time
conditions:
  - condition: state
    entity_id: input_boolean.heating_optimization_enabled
    state: "on"
actions:
  - action: climate.set_hvac_mode
    target:
      entity_id: climate.e3_vitodens_100_0421_1_heating
    data:
      hvac_mode: heat
  - action: number.set_value
    target:
      entity_id: number.e3_vitodens_100_0421_1_normal_temperature
    data:
      value: "{{ states('input_number.heating_optimal_setpoint') }}"
  - action: notify.mobile_app_sadats_iphone_15_olx
    data:
      title: "Heating"
      message: "Heating ON - setpoint {{ states('input_number.heating_optimal_setpoint') }}°C"
mode: single
