alias: "Bathroom: Motion Light OFF"
description: "Turns off bathroom light when both motion sensors are clear"
triggers:
  - trigger: state
    entity_id: binary_sensor.motion_sensor_1_occupancy
    to: "off"
    for:
      minutes: 2
  - trigger: state
    entity_id: binary_sensor.motion_sensor_small_1_occupancy
    to: "off"
    for:
      minutes: 2
conditions:
  - condition: state
    entity_id: light.bathroomlight
    state: "on"
  - condition: state
    entity_id: binary_sensor.motion_sensor_1_occupancy
    state: "off"
  - condition: state
    entity_id: binary_sensor.motion_sensor_small_1_occupancy
    state: "off"
actions:
  - action: light.turn_off
    target:
      entity_id: light.bathroomlight
mode: single
